<?php

$countries = [
    'Antarctica',
    'Antigua and Barbuda',
    'Bolivia, Plurinational State of',
    'Bonaire, Sint Eustatius and Saba',
    'Bosnia and Herzegovina',
    'Bouvet Island',
    'Cabo Verde',
    'Congo',
    'Congo, the Democratic Republic of the',
    'Curaçao',
    'Côte d\'Ivoire',
    'French Southern Territories',
    'Heard Island and McDonald Islands',
    'Iran, Islamic Republic of',
    'Isle of Man',
    'Korea (the Democratic People\'s Republic of)',
    'Korea (the Republic of)',
    'Lao People\'s Democratic Republic',
    'Libya',
    'Macedonia, the former Yugoslav Republic of',
    'Micronesia, Federated States of',
    'Moldova, Republic of',
    'Niue',
    'Norfolk Island',
    'Palestine, State of',
    'Pitcairn',
    'Réunion',
    'Saint Barthélemy',
    'Saint Helena, Ascension and Tristan da Cunha',
    'Saint Kitts and Nevis',
    'Saint Martin (French part)',
    'Saint Pierre and Miquelon',
    'Saint Vincent and the Grenadines',
    'Sao Tome and Principe',
    'Sint Maarten (Dutch part)',
    'South Georgia and the South Sandwich Islands',
    'South Sudan',
    'Svalbard and Jan Mayen',
    'Taiwan, Province of China&nbsp;[note 2]',
    'Tanzania, United Republic of',
    'Timor-Leste',
    'Trinidad and Tobago',
    'Turks and Caicos Islands',
    'United States Minor Outlying Islands',
    'Venezuela, Bolivarian Republic of',
    'Viet Nam',
    'Virgin Islands, British',
    'Wallis and Futuna',
    'Åland Islands',
];
